# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2




    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy --file /home/ec2-user/actions-runner/_work/simple-java-maven-app5/simple-java-maven-app5/pom.xml
      env:
        GITHUB_TOKEN: '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'
